"""SCNSim — Superconducting Circuit Network Simulation.

This package implements the Human-accepted and stabilized Full V1 public
semantics taught in Lessons 1--13. Stabilization remains separate from release
delivery.

Start with :class:`CircuitPlan` if you develop reusable circuit models.  Start
with :class:`CircuitRun` plus a model package supplied by your team if you only
consume an existing model.
"""

from importlib.metadata import version as metadata_version

from . import units
from .authoring import (
    RLGC,
    AffineMap,
    CircuitPlan,
    ComponentInstance,
    CompositePlan,
    CoordinateRef,
    ElectricNodeRef,
    InductiveBranchRef,
    Library,
    ParameterRef,
    ParameterSet,
    ParameterSpec,
    PinRef,
    PortRef,
    components,
)
from .errors import (
    BackendProtocolError,
    CompilerInvariantError,
    DirectResponseFormationError,
    EliminatedBlockSolveFailure,
    EvidenceIntegrityError,
    HBCaseFailure,
    InvalidCandidatePhysicalParameter,
    InvalidDiagonalRootHint,
    InvalidOptimizationSpec,
    NumericalResolutionUnresolved,
    PlanSealedError,
    PortRealizabilityError,
    ResultUnavailableError,
    RootSlopeUnresolved,
    RuntimePreparationError,
    ScaffoldUnavailableError,
    SCNSimCapabilityError,
    SCNSimError,
    SCNSimEvidenceError,
    SCNSimExecutionError,
    SCNSimStateError,
    SCNSimValidationError,
    UnsupportedRuntimePlatformError,
    UnsupportedSingularCapacitanceForDiagonalRootV1,
    WorkspacePlanReplacedError,
    WorkspaceVersioningDowngradeForbidden,
)
from .io import load_q2d_rlgc
from .presentation import Theme
from .results import (
    AnalysisResult,
    BiasState,
    CircuitDiagramResult,
    DiagonalRootResult,
    DirectQuantityResult,
    DirectSolveResult,
    ExplanationResult,
    HBBatchResult,
    HBCaseOutcome,
    HBScatteringMatrixResult,
    InventoryResult,
    MatrixFamilyResult,
    MatrixView,
    OperatorPointResult,
    OperatorResult,
    OptimizationBest,
    OptimizationResult,
    PumpState,
    ReconciliationEvidence,
    ReportResult,
    Result,
    ResultIdentity,
    ScatteringMatrixResult,
    TraceResult,
)
from .runtime import CircuitRun, NetworkViewRef, ReductionPipeline
from .specs import (
    CircuitDiagramSpec,
    CMAESSpec,
    CostObjective,
    CurrentDrive,
    DiagonalRootSpec,
    DirectSolveSpec,
    HBCaseSpec,
    HBSolveSpec,
    HBTruncation,
    HybridizedPoleSpec,
    OperatorSpec,
    OptimizationSpec,
    OptimizationVariable,
    PumpAxis,
    QuantitySum,
    ReportSpec,
    ResidueNormalizedCouplingSpec,
    ResponseElementSpec,
    DiagramSide,
    SParameterTrace,
    SchematicGroup,
    SchematicLayout,
    SchematicPath,
    TransferZeroSpec,
)

__version__ = metadata_version("scnsim")

__all__ = [
    "RLGC",
    "AffineMap",
    "AnalysisResult",
    "BackendProtocolError",
    "BiasState",
    "CMAESSpec",
    "CircuitDiagramResult",
    "CircuitDiagramSpec",
    "CircuitPlan",
    "CircuitRun",
    "CompilerInvariantError",
    "ComponentInstance",
    "CompositePlan",
    "CoordinateRef",
    "CostObjective",
    "CurrentDrive",
    "DiagonalRootResult",
    "DiagonalRootSpec",
    "DirectQuantityResult",
    "DirectResponseFormationError",
    "DirectSolveResult",
    "DirectSolveSpec",
    "DiagramSide",
    "ElectricNodeRef",
    "EliminatedBlockSolveFailure",
    "EvidenceIntegrityError",
    "ExplanationResult",
    "HBBatchResult",
    "HBCaseFailure",
    "HBCaseOutcome",
    "HBCaseSpec",
    "HBScatteringMatrixResult",
    "HBSolveSpec",
    "HBTruncation",
    "HybridizedPoleSpec",
    "InductiveBranchRef",
    "InvalidCandidatePhysicalParameter",
    "InvalidDiagonalRootHint",
    "InvalidOptimizationSpec",
    "InventoryResult",
    "Library",
    "MatrixFamilyResult",
    "MatrixView",
    "NetworkViewRef",
    "NumericalResolutionUnresolved",
    "OperatorPointResult",
    "OperatorResult",
    "OperatorSpec",
    "OptimizationBest",
    "OptimizationResult",
    "OptimizationSpec",
    "OptimizationVariable",
    "ParameterRef",
    "ParameterSet",
    "ParameterSpec",
    "PinRef",
    "PlanSealedError",
    "PortRealizabilityError",
    "PortRef",
    "PumpAxis",
    "PumpState",
    "QuantitySum",
    "ReconciliationEvidence",
    "ReductionPipeline",
    "ReportResult",
    "ReportSpec",
    "ResidueNormalizedCouplingSpec",
    "ResponseElementSpec",
    "Result",
    "ResultIdentity",
    "ResultUnavailableError",
    "RootSlopeUnresolved",
    "RuntimePreparationError",
    "SCNSimCapabilityError",
    "SCNSimError",
    "SCNSimEvidenceError",
    "SCNSimExecutionError",
    "SCNSimStateError",
    "SCNSimValidationError",
    "SParameterTrace",
    "SchematicGroup",
    "SchematicLayout",
    "SchematicPath",
    "ScaffoldUnavailableError",
    "ScatteringMatrixResult",
    "TraceResult",
    "Theme",
    "TransferZeroSpec",
    "UnsupportedRuntimePlatformError",
    "UnsupportedSingularCapacitanceForDiagonalRootV1",
    "WorkspacePlanReplacedError",
    "WorkspaceVersioningDowngradeForbidden",
    "components",
    "load_q2d_rlgc",
    "units",
]
