[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "scnsim"
version = "1.0.0.dev3"
description = "Superconducting Circuit Network Simulation."
readme = "README.md"
requires-python = ">=3.10"
license = "Apache-2.0"
license-files = ["LICENSE", "NOTICE"]
dependencies = [
  "juliapkg>=0.1.26,<0.2",
  "matplotlib>=3.10.9,<3.11",
  "numpy>=2.2.6,<2.3",
  "pint>=0.24.4,<0.25",
  "schemdraw>=0.23,<1",
  "zarr>=2.18.3,<3",
]

[project.urls]
Homepage = "https://github.com/OrPenStrike/scnsim"
Documentation = "https://github.com/OrPenStrike/scnsim/blob/develop/docs/index.qmd"
Issues = "https://github.com/OrPenStrike/scnsim/issues"
Repository = "https://github.com/OrPenStrike/scnsim"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
scnsim = [
  "py.typed",
  "_schemas/*.json",
  "_julia/*.toml",
  "_julia/*.json",
  "_julia/bin/*.jl",
  "_julia/src/*.jl",
]
