"""Finite, deterministic orthogonal routing for neutral schematic scenes.

The router accepts transient placement demands only.  In particular, net and
scope identities stop at this boundary: callers receive polylines and jump
facts which can be emitted into a :class:`NeutralScene` without retaining a
second electrical or ownership table in that scene.
"""

from __future__ import annotations

import heapq
from bisect import bisect_left, bisect_right
from collections import Counter, OrderedDict, defaultdict
from collections.abc import Iterable, Mapping, Sequence
from dataclasses import dataclass
from contextlib import contextmanager
from contextvars import ContextVar
from functools import wraps
from itertools import combinations, pairwise

from ..errors import SCNSimValidationError
from .metrics import DiagramMetrics
from .native import jump_arc
from .scene import COORDINATE_TOLERANCE, Bounds, ConductivePolyline, JumpArc, Point


_geometry_workspace: ContextVar[OrderedDict | None] = ContextVar("scnsim_visibility_workspace", default=None)


@contextmanager
def routing_workspace():
    """One render's exact-geometry reuse; never survives or leaks to a later call."""
    token = _geometry_workspace.set(OrderedDict())
    try:
        yield
    finally:
        _geometry_workspace.reset(token)


def _memoized_geometry(function):
    @wraps(function)
    def measured(*args, **kwargs):
        workspace = _geometry_workspace.get()
        if workspace is None:
            return function(*args, **kwargs)
        def immutable(value):
            return tuple(immutable(item) for item in value) if isinstance(value,(list,tuple)) else value
        key = (function.__name__, immutable(args), tuple((name,immutable(value)) for name,value in sorted(kwargs.items())))
        if key in workspace:
            workspace.move_to_end(key)
            return workspace[key]
        result = function(*args, **kwargs)
        # Memory eviction changes only reuse, never the candidate set or route.
        # The total cached lattice/graph vertex count is bounded per render.
        if len(result) <= 65536:
            while workspace and (len(workspace) >= 128 or sum(len(value) for value in workspace.values()) + len(result) > 65536):
                workspace.popitem(last=False)
            workspace[key] = result
        return result
    return measured


def _failure(message: str, **evidence: object) -> SCNSimValidationError:
    return SCNSimValidationError(message, stage="schematic_layout", evidence=evidence)


class RoutingCandidateRejected(SCNSimValidationError):
    """A valid measured routing candidate could not be completed by this strategy.

    Only this exception permits trying another geometric candidate. Malformed
    demands and internal protocol failures retain their ordinary error types.
    """

    def __init__(self, message: str, **evidence: object) -> None:
        super().__init__(message, stage="schematic_layout", evidence=evidence)


@dataclass(frozen=True, slots=True)
class WireDemand:
    """One transient same-net routing request generated by layout.

    ``net_key`` and ``scope_key`` are deliberately private routing inputs;
    neither can be recovered from the returned geometry or stored in the
    neutral scene.  ``ingress`` lists the registered region-entry anchors
    available to this demand.  A demand may only traverse the supplied allowed
    region and its exact terminals/ingress points.
    """

    net_key: str
    scope_key: tuple[str, ...]
    terminals: tuple[Point, ...]
    allowed_region: Bounds
    ingress: tuple[Point, ...] = ()
    escapes: tuple[tuple[Point, Point], ...] = ()

    def __post_init__(self) -> None:
        if not isinstance(self.net_key, str) or not self.net_key:
            raise ValueError("wire demand net_key must be a nonempty string")
        if len(self.terminals) < 2:
            raise ValueError("wire demands require at least two terminals")
        if len(set(self.terminals)) != len(self.terminals):
            raise ValueError("wire demand terminals must be distinct")
        if not all(_in_bounds(point, self.allowed_region) for point in self.terminals):
            raise ValueError("wire demand terminal lies outside its allowed region")
        if not all(_in_bounds(point, self.allowed_region) for point in self.ingress):
            raise ValueError("wire demand ingress lies outside its allowed region")


@dataclass(frozen=True, slots=True)
class RoutedGeometry:
    """Geometry produced by one bounded routing pass, without demand facts."""

    conductive: tuple[ConductivePolyline, ...]
    jumps: tuple[JumpArc, ...]
    length: float
    bends: int


def _in_bounds(point: Point, bounds: Bounds) -> bool:
    return (
        bounds.xmin - COORDINATE_TOLERANCE
        <= point.x
        <= bounds.xmax + COORDINATE_TOLERANCE
        and bounds.ymin - COORDINATE_TOLERANCE
        <= point.y
        <= bounds.ymax + COORDINATE_TOLERANCE
    )


def _inside(point: Point, bounds: Bounds) -> bool:
    return (
        bounds.xmin + COORDINATE_TOLERANCE
        < point.x
        < bounds.xmax - COORDINATE_TOLERANCE
        and bounds.ymin + COORDINATE_TOLERANCE
        < point.y
        < bounds.ymax - COORDINATE_TOLERANCE
    )


def _inflate(bounds: Bounds, clearance: float) -> Bounds:
    return Bounds(
        bounds.xmin - clearance,
        bounds.ymin - clearance,
        bounds.xmax + clearance,
        bounds.ymax + clearance,
    )


def _segment_clear(first: Point, second: Point, obstacles: Sequence[Bounds]) -> bool:
    """Whether an axis-aligned segment avoids all obstacle interiors."""

    if abs(first.x - second.x) <= COORDINATE_TOLERANCE:
        x = first.x
        low, high = sorted((first.y, second.y))
        for obstacle in obstacles:
            if (
                obstacle.xmin + COORDINATE_TOLERANCE
                < x
                < obstacle.xmax - COORDINATE_TOLERANCE
                and low < obstacle.ymax - COORDINATE_TOLERANCE
                and high > obstacle.ymin + COORDINATE_TOLERANCE
            ):
                return False
        return True
    if abs(first.y - second.y) <= COORDINATE_TOLERANCE:
        y = first.y
        low, high = sorted((first.x, second.x))
        for obstacle in obstacles:
            if (
                obstacle.ymin + COORDINATE_TOLERANCE
                < y
                < obstacle.ymax - COORDINATE_TOLERANCE
                and low < obstacle.xmax - COORDINATE_TOLERANCE
                and high > obstacle.xmin + COORDINATE_TOLERANCE
            ):
                return False
        return True
    return False


def _canonical_points(points: Iterable[Point]) -> tuple[Point, ...]:
    return tuple(
        sorted({_snap(point) for point in points}, key=lambda point: (point.x, point.y))
    )


def _snap(point: Point) -> Point:
    """Use the scene's existing contact precision for visibility identities."""
    return Point(
        round(point.x / COORDINATE_TOLERANCE) * COORDINATE_TOLERANCE,
        round(point.y / COORDINATE_TOLERANCE) * COORDINATE_TOLERANCE,
    )


@_memoized_geometry
def _visibility_vertices(
    demand: WireDemand,
    obstacles: Sequence[Bounds],
    metrics: DiagramMetrics,
    *,
    keepouts: Sequence[Bounds] = (),
) -> tuple[Point, ...]:
    """Build one finite anchor/projection/corridor/detour visibility lattice."""

    allowed = demand.allowed_region
    inflated = (
        *(_inflate(item, metrics.obstacle_clearance) for item in obstacles),
        *keepouts,
    )
    pitch = metrics.routing_lane_pitch
    xs = {allowed.xmin, allowed.xmax}
    ys = {allowed.ymin, allowed.ymax}
    for point in (*demand.terminals, *demand.ingress):
        xs.add(point.x)
        ys.add(point.y)
    for obstacle in inflated:
        xs.update(
            (obstacle.xmin, obstacle.xmax, obstacle.xmin - pitch, obstacle.xmax + pitch)
        )
        ys.update(
            (obstacle.ymin, obstacle.ymax, obstacle.ymin - pitch, obstacle.ymax + pitch)
        )
    # The enclosing rectangle gives a finite honest detour route when internal
    # corridors are blocked.  It remains inside the scope's allowed extent.
    points = []
    visible_ys = sorted(
        y
        for y in ys
        if allowed.ymin - COORDINATE_TOLERANCE
        <= y
        <= allowed.ymax + COORDINATE_TOLERANCE
    )
    for x in sorted(
        value
        for value in xs
        if allowed.xmin - COORDINATE_TOLERANCE
        <= value
        <= allowed.xmax + COORDINATE_TOLERANCE
    ):
        intervals = sorted(
            (item.ymin + COORDINATE_TOLERANCE, item.ymax - COORDINATE_TOLERANCE)
            for item in inflated
            if item.xmin + COORDINATE_TOLERANCE < x < item.xmax - COORDINATE_TOLERANCE
        )
        cursor = 0
        blocked_until = float("-inf")
        for y in visible_ys:
            while cursor < len(intervals) and intervals[cursor][0] < y:
                blocked_until = max(blocked_until, intervals[cursor][1])
                cursor += 1
            if y >= blocked_until:
                points.append(Point(x, y))
    points.extend(demand.terminals)
    points.extend(demand.ingress)
    return _canonical_points(points)


def _edge_interactions(
    first: Point,
    second: Point,
    occupied: Sequence[tuple[Point, Point]],
    *,
    jump_gap: float,
) -> tuple[bool, int]:
    """Return forbidden/crossing facts against already routed other nets."""

    vertical = abs(first.x - second.x) <= COORDINATE_TOLERANCE
    crossings = 0
    for left, right in occupied:
        other_vertical = abs(left.x - right.x) <= COORDINATE_TOLERANCE
        if vertical == other_vertical:
            if vertical and abs(first.x - left.x) <= COORDINATE_TOLERANCE:
                low = max(min(first.y, second.y), min(left.y, right.y))
                high = min(max(first.y, second.y), max(left.y, right.y))
                if high >= low - COORDINATE_TOLERANCE:
                    return True, 0
            if not vertical and abs(first.y - left.y) <= COORDINATE_TOLERANCE:
                low = max(min(first.x, second.x), min(left.x, right.x))
                high = min(max(first.x, second.x), max(left.x, right.x))
                if high >= low - COORDINATE_TOLERANCE:
                    return True, 0
            continue
        vertical_segment, horizontal_segment = (
            ((first, second), (left, right))
            if vertical
            else ((left, right), (first, second))
        )
        crossing = Point(vertical_segment[0].x, horizontal_segment[0].y)
        vlow, vhigh = sorted((vertical_segment[0].y, vertical_segment[1].y))
        hlow, hhigh = sorted((horizontal_segment[0].x, horizontal_segment[1].x))
        if (
            vlow - COORDINATE_TOLERANCE <= crossing.y <= vhigh + COORDINATE_TOLERANCE
            and hlow - COORDINATE_TOLERANCE
            <= crossing.x
            <= hhigh + COORDINATE_TOLERANCE
        ):
            # Different nets may cross only in the interiors with sufficient
            # span to replace the jumped interval by an actual raised arc.
            if not (
                vlow + jump_gap < crossing.y < vhigh - jump_gap
                and hlow + jump_gap < crossing.x < hhigh - jump_gap
            ):
                return True, 0
            crossings += 1
    return False, crossings


@_memoized_geometry
def _visibility_graph(
    vertices: Sequence[Point],
    obstacles: Sequence[Bounds],
    occupied: Sequence[tuple[Point, Point]],
    *,
    jump_gap: float,
    anchors: frozenset[Point],
) -> dict[Point, tuple[tuple[Point, tuple[int, float]], ...]]:
    adjacency: dict[Point, list[tuple[Point, tuple[int, float]]]] = {
        point: [] for point in vertices
    }
    by_x: dict[float, list[Point]] = {}
    by_y: dict[float, list[Point]] = {}
    vertical_strokes = sorted(
        (
            (left.x, min(left.y, right.y), max(left.y, right.y), left, right)
            for left, right in occupied
            if abs(left.x - right.x) <= COORDINATE_TOLERANCE
        ),
        key=lambda row: row[:3],
    )
    horizontal_strokes = sorted(
        (
            (left.y, min(left.x, right.x), max(left.x, right.x), left, right)
            for left, right in occupied
            if abs(left.x - right.x) > COORDINATE_TOLERANCE
        ),
        key=lambda row: row[:3],
    )
    vertical_coordinates = [row[0] for row in vertical_strokes]
    horizontal_coordinates = [row[0] for row in horizontal_strokes]

    def near_stroke(point: Point) -> bool:
        for rows, coordinates, cross, along in (
            (vertical_strokes, vertical_coordinates, point.x, point.y),
            (horizontal_strokes, horizontal_coordinates, point.y, point.x),
        ):
            nearby = rows[
                bisect_left(
                    coordinates, cross - jump_gap - COORDINATE_TOLERANCE
                ) : bisect_right(coordinates, cross + jump_gap + COORDINATE_TOLERANCE)
            ]
            if any(
                row[1] - jump_gap - COORDINATE_TOLERANCE
                <= along
                <= row[2] + jump_gap + COORDINATE_TOLERANCE
                for row in nearby
            ):
                return True
        return False

    for point in vertices:
        # A crossing is an edge interior, never a graph vertex at which a
        # new net may stop or turn.  Keep vertices clear of existing foreign
        # strokes so the adjacent visibility edge can span the whole jump.
        # Otherwise a terminal-projection row splits every possible crossing
        # into two prohibited endpoint contacts and seals an artificial wall.
        if point not in anchors and near_stroke(point):
            continue
        by_x.setdefault(point.x, []).append(point)
        by_y.setdefault(point.y, []).append(point)

    def interacting_strokes(
        first: Point, second: Point
    ) -> tuple[tuple[Point, Point], ...]:
        vertical = abs(first.x - second.x) <= COORDINATE_TOLERANCE
        parallel, parallel_coordinates = (
            (vertical_strokes, vertical_coordinates)
            if vertical
            else (horizontal_strokes, horizontal_coordinates)
        )
        perpendicular, perpendicular_coordinates = (
            (horizontal_strokes, horizontal_coordinates)
            if vertical
            else (vertical_strokes, vertical_coordinates)
        )
        coordinate = first.x if vertical else first.y
        low, high = sorted((first.y, second.y) if vertical else (first.x, second.x))
        relevant = [
            (row[3], row[4])
            for row in parallel[
                bisect_left(
                    parallel_coordinates, coordinate - COORDINATE_TOLERANCE
                ) : bisect_right(
                    parallel_coordinates, coordinate + COORDINATE_TOLERANCE
                )
            ]
            if row[1] <= high + COORDINATE_TOLERANCE
            and row[2] >= low - COORDINATE_TOLERANCE
        ]
        relevant.extend(
            (row[3], row[4])
            for row in perpendicular[
                bisect_left(
                    perpendicular_coordinates, low - COORDINATE_TOLERANCE
                ) : bisect_right(perpendicular_coordinates, high + COORDINATE_TOLERANCE)
            ]
            if row[1] - COORDINATE_TOLERANCE
            <= coordinate
            <= row[2] + COORDINATE_TOLERANCE
        )
        return tuple(relevant)

    for rows, axis in ((by_x.values(), "y"), (by_y.values(), "x")):
        for row in rows:
            ordered = sorted(row, key=lambda point: getattr(point, axis))
            transverse = ordered[0].x if axis == "y" else ordered[0].y
            # Every edge in this row has the same transverse coordinate.
            # Filter stroke spans once, not once per visibility edge. The
            # sorted crossing coordinates then provide exact range queries.
            parallel_rows, parallel_coordinates = (
                (vertical_strokes, vertical_coordinates) if axis == "y"
                else (horizontal_strokes, horizontal_coordinates)
            )
            perpendicular_rows = horizontal_strokes if axis == "y" else vertical_strokes
            row_parallel = parallel_rows[
                bisect_left(parallel_coordinates, transverse-COORDINATE_TOLERANCE):
                bisect_right(parallel_coordinates, transverse+COORDINATE_TOLERANCE)
            ]
            row_crossings = tuple(
                item for item in perpendicular_rows
                if item[1]-COORDINATE_TOLERANCE <= transverse <= item[2]+COORDINATE_TOLERANCE
            )
            along_coordinates = tuple(getattr(point,axis) for point in ordered)
            interactions: dict[int, list[tuple[Point,Point]]] = defaultdict(list)
            for item in (*row_parallel, *row_crossings):
                low, high = (item[1],item[2]) if item in row_parallel else (item[0],item[0])
                first_edge = max(0,bisect_left(along_coordinates,low-COORDINATE_TOLERANCE)-1)
                stop_edge = min(len(ordered)-1,bisect_right(along_coordinates,high+COORDINATE_TOLERANCE))
                for edge in range(first_edge,stop_edge):
                    interactions[edge].append((item[3],item[4]))
            intervals = sorted(
                (item.ymin + COORDINATE_TOLERANCE, item.ymax - COORDINATE_TOLERANCE)
                if axis == "y"
                else (
                    item.xmin + COORDINATE_TOLERANCE,
                    item.xmax - COORDINATE_TOLERANCE,
                )
                for item in obstacles
                if (
                    (
                        item.xmin + COORDINATE_TOLERANCE
                        < transverse
                        < item.xmax - COORDINATE_TOLERANCE
                    )
                    if axis == "y"
                    else (
                        item.ymin + COORDINATE_TOLERANCE
                        < transverse
                        < item.ymax - COORDINATE_TOLERANCE
                    )
                )
            )
            cursor = 0
            for edge, (first, second) in enumerate(pairwise(ordered)):
                low, high = getattr(first, axis), getattr(second, axis)
                while cursor < len(intervals) and intervals[cursor][1] <= low:
                    cursor += 1
                if cursor < len(intervals) and intervals[cursor][0] < high:
                    continue
                if axis == "x" and abs(first.x-second.x) <= COORDINATE_TOLERANCE:
                    # Preserve the existing tolerance classification for a
                    # shortest horizontal grid edge at the contact precision.
                    relevant = interacting_strokes(first, second)
                else:
                    relevant = interactions.get(edge, ())
                blocked, crossings = _edge_interactions(first,second,relevant,jump_gap=jump_gap) if relevant else (False,0)
                if not blocked:
                    # Costs use the scene's existing coordinate precision.
                    # Splitting a straight corridor into more visibility edges
                    # must not gain a floating-point rounding advantage over
                    # an equal-length, lower-bend path.
                    cost = abs(
                        round(first.x / COORDINATE_TOLERANCE)
                        - round(second.x / COORDINATE_TOLERANCE)
                    ) + abs(
                        round(first.y / COORDINATE_TOLERANCE)
                        - round(second.y / COORDINATE_TOLERANCE)
                    )
                    adjacency[first].append((second, (crossings, cost)))
                    adjacency[second].append((first, (crossings, cost)))
    return {
        point: tuple(sorted(rows, key=lambda item: (item[1], item[0].x, item[0].y)))
        for point, rows in adjacency.items()
    }


def _shortest_path(
    graph: dict[Point, tuple[tuple[Point, tuple[int, float]], ...]],
    start: Point,
    destinations: set[Point],
    *,
    crossing_cost: float | None = None,
    bend_cost: float = 0.0,
) -> tuple[Point, ...] | None:
    """Dijkstra with canonical equal-cost selection.

    The graph is finite.  A full path tuple in the priority key makes every
    equal-cost choice deterministic without relying on object allocation order.
    """

    pending: list[
        tuple[
            tuple[float, int, int, float],
            tuple[tuple[float, float], ...],
            Point,
            tuple[Point, ...],
        ]
    ] = []
    initial_key = ((start.x, start.y),)
    heapq.heappush(pending, ((0.0, 0, 0, 0.0), initial_key, start, (start,)))
    best: dict[
        tuple[Point, str],
        tuple[tuple[float, int, int, float], tuple[tuple[float, float], ...]],
    ] = {(start, "start"): ((0.0, 0, 0, 0.0), initial_key)}
    crossing_weight = 0 if crossing_cost is None else round(crossing_cost / COORDINATE_TOLERANCE)
    bend_weight = round(bend_cost / COORDINATE_TOLERANCE)
    while pending:
        cost, key, point, path = heapq.heappop(pending)
        incoming_axis = (
            "start"
            if len(path) == 1
            else "vertical"
            if abs(path[-2].x - point.x) <= COORDINATE_TOLERANCE
            else "horizontal"
        )
        state = (point, incoming_axis)
        prior = best.get(state)
        if prior is not None and prior < (cost, key):
            continue
        if point in destinations:
            return path
        for other, edge_cost in graph.get(point, ()):
            bend = int(len(path) > 1 and not _collinear(path[-2], point, other))
            next_cost = (cost[0]+edge_cost[0],cost[1]+edge_cost[1],cost[2]+bend,0.0) if crossing_cost is None else (
                cost[0] + edge_cost[1] + crossing_weight * edge_cost[0] + bend_weight * bend,
                cost[1] + edge_cost[0], cost[2] + bend, cost[3] + edge_cost[1],
            )
            next_state = (
                other,
                "vertical"
                if abs(point.x - other.x) <= COORDINATE_TOLERANCE
                else "horizontal",
            )
            next_key = (*key, (other.x, other.y))
            prior = best.get(next_state)
            if prior is not None and prior <= (next_cost, next_key):
                continue
            best[next_state] = (next_cost, next_key)
            next_path = (*path, other)
            heapq.heappush(pending, (next_cost, next_key, other, next_path))
    return None


def _compress(points: Sequence[Point]) -> tuple[Point, ...]:
    result: list[Point] = []
    for point in points:
        if result and point == result[-1]:
            continue
        if len(result) >= 2:
            first, middle = result[-2:]
            if (
                abs(first.x - middle.x) <= COORDINATE_TOLERANCE
                and abs(middle.x - point.x) <= COORDINATE_TOLERANCE
            ) or (
                abs(first.y - middle.y) <= COORDINATE_TOLERANCE
                and abs(middle.y - point.y) <= COORDINATE_TOLERANCE
            ):
                result[-1] = point
                continue
        result.append(point)
    return tuple(result)


def _segments(polyline: ConductivePolyline) -> tuple[tuple[Point, Point], ...]:
    return tuple(zip(polyline.points, polyline.points[1:]))


def _on_segment(point: Point, first: Point, second: Point) -> bool:
    if abs(first.x - second.x) <= COORDINATE_TOLERANCE:
        return (
            abs(point.x - first.x) <= COORDINATE_TOLERANCE
            and min(first.y, second.y) - COORDINATE_TOLERANCE
            <= point.y
            <= max(first.y, second.y) + COORDINATE_TOLERANCE
        )
    return (
        abs(point.y - first.y) <= COORDINATE_TOLERANCE
        and min(first.x, second.x) - COORDINATE_TOLERANCE
        <= point.x
        <= max(first.x, second.x) + COORDINATE_TOLERANCE
    )


def _deduplicate(
    polylines: Sequence[ConductivePolyline], owners: Sequence[str]
) -> tuple[list[ConductivePolyline], list[str]]:
    """Emit each same-net collinear interval once, including pre-routed leads."""
    intervals: dict[tuple[str, bool, float], list[tuple[float, float]]] = defaultdict(
        list
    )
    for wire, owner in zip(polylines, owners):
        for first, second in _segments(wire):
            vertical = abs(first.x - second.x) <= COORDINATE_TOLERANCE
            if not vertical and abs(first.y - second.y) > COORDINATE_TOLERANCE:
                raise _failure("existing conductive stroke is not orthogonal")
            coordinate = first.x if vertical else first.y
            low, high = sorted((first.y, second.y) if vertical else (first.x, second.x))
            if high - low > COORDINATE_TOLERANCE:
                intervals[(owner, vertical, coordinate)].append((low, high))
    result, result_owners = [], []
    for (owner, vertical, coordinate), rows in sorted(intervals.items()):
        merged: list[list[float]] = []
        for low, high in sorted(rows):
            if merged and low <= merged[-1][1] + COORDINATE_TOLERANCE:
                merged[-1][1] = max(merged[-1][1], high)
            else:
                merged.append([low, high])
        for low, high in merged:
            a, b = (
                (Point(coordinate, low), Point(coordinate, high))
                if vertical
                else (Point(low, coordinate), Point(high, coordinate))
            )
            result.append(ConductivePolyline((a, b)))
            result_owners.append(owner)
    return result, result_owners


def _collinear(first: Point, middle: Point, last: Point) -> bool:
    return (
        abs(first.x - middle.x) <= COORDINATE_TOLERANCE
        and abs(middle.x - last.x) <= COORDINATE_TOLERANCE
    ) or (
        abs(first.y - middle.y) <= COORDINATE_TOLERANCE
        and abs(middle.y - last.y) <= COORDINATE_TOLERANCE
    )


def _interior_crossing(
    first: tuple[Point, Point], second: tuple[Point, Point]
) -> Point | None:
    (a, b), (c, d) = first, second
    a_vertical = abs(a.x - b.x) <= COORDINATE_TOLERANCE
    c_vertical = abs(c.x - d.x) <= COORDINATE_TOLERANCE
    if a_vertical == c_vertical:
        return None
    vertical, horizontal = ((a, b), (c, d)) if a_vertical else ((c, d), (a, b))
    point = Point(vertical[0].x, horizontal[0].y)
    if (
        min(vertical[0].y, vertical[1].y) + COORDINATE_TOLERANCE
        < point.y
        < max(vertical[0].y, vertical[1].y) - COORDINATE_TOLERANCE
        and min(horizontal[0].x, horizontal[1].x) + COORDINATE_TOLERANCE
        < point.x
        < max(horizontal[0].x, horizontal[1].x) - COORDINATE_TOLERANCE
    ):
        return point
    return None


def _split_jumps(
    polylines: Sequence[ConductivePolyline],
    owners: Sequence[str],
    metrics: DiagramMetrics,
) -> tuple[tuple[ConductivePolyline, ...], tuple[JumpArc, ...]]:
    """Replace jumped horizontal conductor intervals by actual cubic arcs."""

    cuts: dict[tuple[int, int], list[float]] = defaultdict(list)
    arcs: list[JumpArc] = []
    for (index, first), (other_index, second) in combinations(enumerate(polylines), 2):
        if owners[index] == owners[other_index]:
            continue
        for segment_index, first_segment in enumerate(_segments(first)):
            for other_segment_index, second_segment in enumerate(_segments(second)):
                crossing = _interior_crossing(first_segment, second_segment)
                if crossing is None:
                    continue
                # The horizontal conductor is always the jumped wire.  This
                # makes the emitted arc and deleted interval deterministic.
                target_index, target_segment = (
                    (index, segment_index)
                    if abs(first_segment[0].y - first_segment[1].y)
                    <= COORDINATE_TOLERANCE
                    else (other_index, other_segment_index)
                )
                cuts[(target_index, target_segment)].append(crossing.x)
                arcs.append(
                    jump_arc(
                        Point(crossing.x - metrics.jump_gap / 2, crossing.y),
                        Point(crossing.x + metrics.jump_gap / 2, crossing.y),
                        metrics=metrics,
                    )
                )
    visible: list[ConductivePolyline] = []
    half = metrics.jump_gap / 2
    for index, polyline in enumerate(polylines):
        for segment_index, (start, end) in enumerate(_segments(polyline)):
            positions = sorted(
                set(cuts.get((index, segment_index), ())), reverse=end.x < start.x
            )
            if not positions:
                visible.append(ConductivePolyline((start, end)))
                continue
            if abs(start.y - end.y) > COORDINATE_TOLERANCE:
                # A vertical segment is never selected as the jumped stroke.
                raise _failure(
                    "routing jump selection chose a non-horizontal conductor"
                )
            direction = 1 if end.x > start.x else -1
            cursor = start
            for x in positions:
                before = Point(x - direction * half, start.y)
                after = Point(x + direction * half, start.y)
                if abs(cursor.x - before.x) <= COORDINATE_TOLERANCE:
                    raise RoutingCandidateRejected(
                        "routing jump clearance leaves no conductive interval"
                    )
                visible.append(ConductivePolyline((cursor, before)))
                cursor = after
            if abs(cursor.x - end.x) <= COORDINATE_TOLERANCE:
                raise RoutingCandidateRejected("routing jump clearance leaves no conductive interval")
            visible.append(ConductivePolyline((cursor, end)))
    return tuple(visible), tuple(arcs)


def _visible_bends(polylines: Sequence[ConductivePolyline]) -> int:
    """Count actual degree-two cardinal corners, including separate-stroke seams.

    Looking at each polyline independently misses escape/path joins and counts
    a turn ending at a T as a bend. This observes the union before jump cuts;
    unrelated crossing strokes have four rays and do not count as corners.
    """
    segments = tuple(segment for wire in polylines for segment in _segments(wire))
    points = []
    for point in sorted({point for segment in segments for point in segment}, key=lambda p: (p.x,p.y)):
        if not any(abs(point.x-old.x)<=COORDINATE_TOLERANCE and abs(point.y-old.y)<=COORDINATE_TOLERANCE for old in points):
            points.append(point)
    bends = 0
    for point in points:
        rays = set()
        for first, last in segments:
            if not _on_segment(point, first, last):
                continue
            for other in (first,last):
                dx,dy=other.x-point.x,other.y-point.y
                if abs(dx)>COORDINATE_TOLERANCE:
                    rays.add((1 if dx>0 else -1,0))
                if abs(dy)>COORDINATE_TOLERANCE:
                    rays.add((0,1 if dy>0 else -1))
        if len(rays)==2 and any(dx for dx,dy in rays) and any(dy for dx,dy in rays):
            bends += 1
    return bends


def _straight_exterior_core(
    demand, escape_map, same_segments, escaped, local_inflated,
    landings, occupied, metrics, reverse_order,
):
    """Recognize only the unobstructed Manhattan core of two inward stubs.

    The registered stubs remain untouched. Any extra same-owner geometry or
    foreign incidence returns to the full visibility search, never a rejection.
    """
    if len(demand.terminals) != 2:
        return None
    low, high = sorted(demand.terminals, key=lambda point: (point.x, point.y))
    if not (low.x == high.x or low.y == high.y):
        return None
    if any(start not in demand.terminals for start in escape_map):
        return None

    def on_interval(point):
        return (
            point.x == low.x and low.y <= point.y <= high.y
            if low.x == high.x
            else point.y == low.y and low.x <= point.x <= high.x
        )

    if any(not on_interval(point) for point in (*escaped, *escape_map.values())):
        return None

    def segment_key(segment):
        return tuple(sorted(segment, key=lambda point: (point.x, point.y)))

    expected = Counter(
        segment_key((start, end))
        for start, end in escape_map.items() if start != end
    )
    if Counter(map(segment_key, same_segments)) != expected:
        return None
    first, second = escape_map.get(low, low), escape_map.get(high, high)
    dimension = "y" if low.x == high.x else "x"
    if getattr(second, dimension) - getattr(first, dimension) <= COORDINATE_TOLERANCE:
        return None
    if not _segment_clear(first, second, (*local_inflated, *landings)):
        return None
    blocked, crossings = _edge_interactions(
        low, high, occupied, jump_gap=metrics.jump_gap
    )
    if blocked or crossings:
        return None
    return (first, second) if reverse_order else (second, first)


def route_demands(
    demands: Sequence[WireDemand],
    *,
    obstacles: Sequence[Bounds],
    metrics: DiagramMetrics,
    reverse_order: bool,
    existing: Sequence[tuple[str, ConductivePolyline]] = (),
    edge_nets: Mapping[str, str] | None = None,
    demand_order: Sequence[int] | None = None,
    readability: bool = False,
) -> RoutedGeometry:
    """Route each finite same-net tree and report only visible geometry.

    Without demand_order, the existing normal/reversed net ordering is retained.
    An explicit permutation names original input-demand indices; reverse_order
    then only reverses terminal traversal. Authoring callers opt into blended
    readability costs, while the default (including compiled) retains its
    original lexicographic crossing/length/bend objective. The caller owns
    retries; this function never relaxes obstacles or returns partial geometry.
    """

    if not isinstance(metrics, DiagramMetrics):
        raise TypeError("route_demands() requires DiagramMetrics")
    if not isinstance(readability, bool):
        raise TypeError("readability must be a bool")
    if demand_order is not None:
        if any(type(index) is not int for index in demand_order):
            raise TypeError("demand_order must contain integer input-demand indices")
        if sorted(demand_order) != list(range(len(demands))):
            raise ValueError("demand_order must be a complete permutation of input demands")
    normalized = []
    indices = range(len(demands)) if demand_order is None else demand_order
    for index in indices:
        item = demands[index]
        terminals = _canonical_points(item.terminals)
        if len(terminals) > 1:
            normalized.append(
                WireDemand(
                    item.net_key,
                    item.scope_key,
                    terminals,
                    item.allowed_region,
                    _canonical_points(item.ingress),
                    tuple((_snap(a), _snap(b)) for a, b in item.escapes),
                )
            )
    ordered_demands = normalized if demand_order is not None else sorted(
        normalized,
        key=lambda item: (item.scope_key, item.net_key),
        reverse=reverse_order,
    )
    # Supplied strokes are real conductive input, not immutable decoration.
    # Return their complete replacement too, since a newly required jump may
    # split an old stroke. Callers must not append the old strokes again.
    all_polylines: list[ConductivePolyline] = []
    owners: list[str] = []
    if any(
        not isinstance(owner, str)
        or not owner
        or not isinstance(wire, ConductivePolyline)
        for owner, wire in existing
    ):
        raise TypeError(
            "existing routing strokes require a net key and ConductivePolyline"
        )
    for owner, wire in existing:
        points = _compress(tuple(_snap(point) for point in wire.points))
        if len(points) > 1:
            all_polylines.append(ConductivePolyline(points))
            owners.append(owner)
    total_length = 0.0
    bends = 0
    active_obstacles = tuple(obstacles)
    inflated = tuple(
        _inflate(item, metrics.obstacle_clearance) for item in active_obstacles
    )
    prepared = []
    for demand in ordered_demands:
        # An obstacle owning a registered terminal permits only that terminal's
        # exit; its remaining geometry stays reserved by the finite lattice.
        # The geometry layer supplies no hidden ownership table, so this is
        # determined solely by the registered visible anchor coordinates.
        escape_map = {}
        for start, end in demand.escapes:
            owning = tuple(item for item in inflated if _in_bounds(start, item))
            # A registered stub specifies the actual anchor and its cardinal
            # direction. Its exterior endpoint is measured from the complete
            # inflated owning ink, not an assumed fixed lead length.
            if owning:
                if start.y == end.y:
                    end = Point(
                        max(end.x, *(item.xmax for item in owning))
                        if end.x > start.x
                        else min(end.x, *(item.xmin for item in owning)),
                        end.y,
                    )
                elif start.x == end.x:
                    end = Point(
                        end.x,
                        max(end.y, *(item.ymax for item in owning))
                        if end.y > start.y
                        else min(end.y, *(item.ymin for item in owning)),
                    )
                else:
                    raise _failure(
                        "registered electrical escape must be cardinal",
                        net=demand.net_key,
                    )
            if not _in_bounds(end, demand.allowed_region):
                raise RoutingCandidateRejected(
                    "measured registered escape leaves its routing region",
                    net=demand.net_key,
                    start=start,
                    end=end,
                    region=demand.allowed_region,
                )
            escape_map[start] = _snap(end)
        prepared.append((demand, escape_map))
        # Reserve every future terminal's real escape before growing any
        # tree.  A prior net must not consume a later terminal's only exit.
        for start, end in escape_map.items():
            if start != end:
                all_polylines.append(ConductivePolyline((start, end)))
                owners.append(demand.net_key)
    for demand, escape_map in prepared:
        escaped = tuple(escape_map.get(point, point) for point in demand.terminals)
        same_segments = tuple(
            segment
            for index, wire in enumerate(all_polylines)
            if owners[index] == demand.net_key
            for segment in _segments(wire)
        )
        same_endpoints = tuple(
            point
            for segment in same_segments
            for point in segment
            if _in_bounds(point, demand.allowed_region)
            and not any(_inside(point, item) for item in inflated)
        )
        escaped = tuple(dict.fromkeys((*escaped, *same_endpoints)))
        routing_demand = WireDemand(
            demand.net_key,
            demand.scope_key,
            escaped if len(escaped) > 1 else demand.terminals,
            demand.allowed_region,
            (*demand.ingress, *escaped),
        )
        # Future endpoints need room for a turn, not merely an unshorted
        # escape stroke.  Respect close native pin pitch by measuring this
        # landing against every other demand's contacts; no uniform frame
        # clearance may swallow a neighbouring terminal.
        own_contacts = (*demand.terminals, *escaped)
        landings = []
        for other, other_escapes in prepared:
            if other.net_key == demand.net_key:
                continue
            for point in (*other.terminals, *other_escapes.values()):
                if not _in_bounds(point, demand.allowed_region):
                    continue
                distance = min(
                    max(abs(point.x - own.x), abs(point.y - own.y))
                    for own in own_contacts
                )
                radius = min(1.5 * metrics.jump_gap, distance / 3)
                landings.append(_inflate(Bounds.around((point,)), radius))
        # Recipe edges share electrical identity only at their requested
        # junction arms. A same-net crossing elsewhere would invent a T/Cross
        # not present in the composition, so retain those edges as obstacles.
        same_net_strokes = tuple(
            Bounds.around(segment)
            for index, polyline in enumerate(all_polylines)
            if edge_nets is not None
            and owners[index] != demand.net_key
            and edge_nets[owners[index]] == edge_nets[demand.net_key]
            for segment in _segments(polyline)
        )
        local_obstacles = (*active_obstacles, *same_net_strokes)
        local_inflated = (
            *inflated,
            *(_inflate(item, metrics.obstacle_clearance) for item in same_net_strokes),
        )
        if not readability:
            vertices = _visibility_vertices(
                routing_demand, local_obstacles, metrics, keepouts=landings
            )
        occupied = tuple(
            segment
            for index, polyline in enumerate(all_polylines)
            if owners[index] != demand.net_key
            for segment in _segments(polyline)
        )
        if not readability:
            graph = _visibility_graph(
                vertices,
                (*local_inflated, *landings),
                occupied,
                jump_gap=metrics.jump_gap,
                anchors=frozenset((*demand.terminals, *escaped)),
            )
        for start, end in escape_map.items():
            owning = tuple(item for item in inflated if _in_bounds(start, item))
            remaining = tuple(item for item in inflated if item not in owning)
            if not _segment_clear(start, end, remaining) or any(
                _inside(end, item) for item in inflated
            ):
                raise RoutingCandidateRejected(
                    "registered anchor escape collides with an occupied obstacle",
                    net=demand.net_key,
                    start=start,
                    end=end,
                    obstacles=tuple(
                        item
                        for item in remaining
                        if not _segment_clear(start, end, (item,))
                    ),
                    endpoint_obstacles=tuple(
                        item for item in inflated if _inside(end, item)
                    ),
                )
            blocked, _ = _edge_interactions(
                start, end, occupied, jump_gap=metrics.jump_gap
            )
            if blocked:
                raise RoutingCandidateRejected(
                    "registered anchor escape contacts another net",
                    net=demand.net_key,
                    start=start,
                    end=end,
                    strokes=tuple(
                        segment
                        for segment in occupied
                        if _edge_interactions(
                            start, end, (segment,), jump_gap=metrics.jump_gap
                        )[0]
                    ),
                )
        if readability:
            core = _straight_exterior_core(
                demand, escape_map, same_segments, escaped, local_inflated,
                landings, occupied, metrics, reverse_order,
            )
            if core is not None:
                all_polylines.append(ConductivePolyline(core))
                owners.append(demand.net_key)
                continue
            vertices = _visibility_vertices(
                routing_demand, local_obstacles, metrics, keepouts=landings
            )
            graph = _visibility_graph(
                vertices,
                (*local_inflated, *landings),
                occupied,
                jump_gap=metrics.jump_gap,
                anchors=frozenset((*demand.terminals, *escaped)),
            )
        terminals = tuple(
            sorted(escaped, key=lambda point: (point.x, point.y), reverse=reverse_order)
        )
        tree = {terminals[0]}
        tree_neighbors: dict[Point, set[Point]] = defaultdict(set)
        old_neighbors: dict[Point, set[Point]] = defaultdict(set)
        for first, second in same_segments:
            row = sorted(
                (point for point in vertices if _on_segment(point, first, second)),
                key=lambda point: (point.x, point.y),
            )
            for left, right in pairwise(row):
                old_neighbors[left].add(right)
                old_neighbors[right].add(left)

        def absorb_existing(
            seed: Point,
            *,
            tree=tree,
            tree_neighbors=tree_neighbors,
            old_neighbors=old_neighbors,
        ) -> None:
            pending = [seed]
            visited = set()
            while pending:
                point = pending.pop()
                if point in visited:
                    continue
                visited.add(point)
                tree.add(point)
                tree_neighbors[point].update(old_neighbors[point])
                pending.extend(old_neighbors[point] - visited)

        absorb_existing(terminals[0])
        for anchor, exterior in escape_map.items():
            tree_neighbors[exterior].add(anchor)
        for terminal in terminals[1:]:
            if terminal in tree:
                continue
            # A fourth arm joins the next available tree vertex, producing
            # staggered Ts directly in the finite lattice. Never move a wire
            # after routing, when that move could enter an unseen obstacle.
            saturated = {point for point in tree if len(tree_neighbors[point]) >= 3}
            branch_graph = {
                point: tuple(row for row in rows if row[0] not in saturated)
                for point, rows in graph.items()
                if point not in saturated
            }
            path = _shortest_path(branch_graph, terminal, tree - saturated,
                crossing_cost=2 * metrics.native_span if readability else None,
                bend_cost=metrics.obstacle_clearance if readability else 0.0)
            if path is None:
                raise RoutingCandidateRejected(
                    f"finite schematic router found no route for required net {demand.net_key!r}",
                    net=demand.net_key,
                    scope=demand.scope_key,
                    terminal=terminal,
                    visible_neighbors=len(branch_graph.get(terminal, ())),
                    graph_neighbors=len(graph.get(terminal, ())),
                    terminal_obstacles=tuple(
                        item for item in inflated if _in_bounds(terminal, item)
                    ),
                    terminal_strokes=tuple(
                        (a, b)
                        for a, b in occupied
                        if _in_bounds(
                            terminal, _inflate(Bounds.around((a, b)), metrics.jump_gap)
                        )
                    ),
                    tree_vertices=len(tree),
                    tree_neighbor_counts=tuple(
                        (point, len(branch_graph.get(point, ())))
                        for point in sorted(tree)[:8]
                    ),
                )
            compressed = _compress(path)
            if len(compressed) < 2:
                raise _failure(
                    "finite schematic router produced a degenerate wire",
                    net=demand.net_key,
                )
            polyline = ConductivePolyline(compressed)
            all_polylines.append(polyline)
            owners.append(demand.net_key)
            # Retain every visibility vertex on the tree, not only its bends.
            # Later branches stop at their first T contact instead of crossing
            # and retracing a same-net conductor.
            tree.update(path)
            for left, right in pairwise(path):
                tree_neighbors[left].add(right)
                tree_neighbors[right].add(left)
            absorb_existing(terminal)
            total_length += sum(
                abs(left.x - right.x) + abs(left.y - right.y)
                for left, right in _segments(polyline)
            )
            bends += max(0, len(compressed) - 2)
    # The tree constructor already emits only T/staggered-T joins. Ranking
    # includes registered stubs, which are real visible conductive length.
    all_polylines, owners = _deduplicate(all_polylines, owners)
    # A semantic contact remains an actual segment endpoint after collinear
    # coalescing.  This preserves observable bus/tap/public-pin incidence
    # without retaining any routing identity in the frozen scene.
    contacts = {point for demand in normalized for point in demand.terminals}
    split, split_owners = [], []
    for wire, owner in zip(all_polylines, owners):
        first, last = wire.points
        points = sorted(
            {
                first,
                last,
                *(point for point in contacts if _on_segment(point, first, last)),
            },
            key=lambda point: (point.x, point.y),
        )
        for left, right in pairwise(points):
            if (
                abs(left.x - right.x) <= COORDINATE_TOLERANCE
                and abs(left.y - right.y) <= COORDINATE_TOLERANCE
            ):
                continue
            split.append(ConductivePolyline((left, right)))
            split_owners.append(owner)
    all_polylines, owners = split, split_owners
    total_length = sum(
        abs(left.x - right.x) + abs(left.y - right.y)
        for polyline in all_polylines
        for left, right in _segments(polyline)
    )
    bends = _visible_bends(all_polylines)
    visible, jumps = _split_jumps(all_polylines, owners, metrics)
    return RoutedGeometry(visible, jumps, total_length, bends)
